### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by pcorbineau** [AtharvShinde/CPP_Vehicle_Management_System#1]
* Keep your code simple. When you see a class with only getter/setter, thats mean you dont need a class. Its a struct. Just do a struct Vehicule for example.
 * Dont push binary on git (Its not recommanded).

**Comment by pcorbineau** [comment]
BTW, Its also a good practice to try to add unit test. You can make a library that main.cpp will use and another executable for test using a test framework like gtest, doctest, catch2 ... Or even simpler using assert from cassert.h

**Comment by pcorbineau** [comment]
Take a loot at #2

**Comment by AtharvShinde** [comment]
Thanks for the suggestions! I'll definitely look into those improvements. Appreciate the insight about using structs instead of classes when only getters and setters are involved, and I'll ensure not to push binaries to Git. Also, I'll explore adding unit tests with frameworks like gtest, doctest, or catch2, or even using simple assertions from <cassert>. Thanks again for the valuable advice!
